config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  # root "posts#index"

  get 'users/index'
  get 'users/show'
  get 'home/index'
  devise_for :users
  root "home#index"

  resources :folders do
    resources :file_uploads, only: [:create, :index, :destroy, :new, :show, :update] do
      member do
        get 'download'
      end

      resources :file_shares, only: [:new, :create], controller: 'file_shares'
    end
  end

  resources :file_shares, only: [] do
    member do
      get 'download'
    end
  end

  resources :users, only: [:index, :show] do
    resources :folders, only: [:index] do
      resources :file_uploads, only: [:index]
    end

    member do
      patch :update_role
    end
  end

  resources :audit_logs, only: [:index]

  resources :notifications, only: [:index]
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  belongs_to :user
  has_one_attached :file
  has_many :file_shares
  belongs_to :folder, optional: false
  
  validates :permission, inclusion: { in: %w[read-only read-write] }
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_file_upload, only: [:destroy, :download, :update, :show]
  
    def index
        @folder = Folder.find(params[:folder_id])
        @file_uploads = if current_user.admin?
                            FileUpload.all
                        elsif current_user.user?
                            current_user.file_uploads
                        elsif current_user.guest?
                            current_user.file_shares.includes(:file_upload).map(&:file_upload)
                        else
                            []
                        end
    end

    def new
        @folder = Folder.find(params[:folder_id])
        @file_upload = @folder.file_uploads.build
    end
  
    def create
        if current_user.user?           
            @folder = Folder.find(params[:folder_id])
            @file_upload = @folder.file_uploads.build(file_upload_params)
            @file_upload.user = current_user

            if @file_upload.save
                log_audit_action('create', 'FileUpload', @file_upload.id)
                redirect_to folder_path(@folder), notice: "File uploaded successfully."
            else
                redirect_to folder_path(@folder), alert: "Unsuccessfully uploaded file"
            end
        else
            redirect_to folder_path(@folder), alert: "Not authorized to upload this file"
        end
    end
  
    def destroy
        if @file_upload.user == current_user 
            @file_upload.destroy
            log_audit_action('destroy', 'FileUpload', @file_upload.id)
            redirect_to file_uploads_path, notice: "File deleted successfully."
        else
            redirect_to file_uploads_path, alert: "Not authorized to delete this file"
        end
    end

    def download
        send_data @file_upload.file.download, filename: @file_upload.name, disposition: 'attachment'
        log_audit_action('download', 'FileUpload', @file_upload.id)
    end

    def update        
        if @file_upload.user == current_user && @file_upload.update(file_upload_params)
            log_audit_action('file permission update', 'FileUpload', @file_upload.id)
            redirect_to folder_file_upload_path(@file_upload.folder, @file_upload), notice: "File updated successfully."        
        else
            render :show
        end
    end

    def show
        @file_upload
    end
  
    private
  
    def set_file_upload
      @file_upload = FileUpload.find(params[:id])
    end
  
    def file_upload_params
      params.require(:file_upload).permit(:file, :name, :permission, :folder_id)
    end
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/views/file_uploads/_form.html.erb
<%= form_with(model: @file_upload, local: true) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.label :file %>
      <%= form.file_field :file %>
    </div>
    <div>
      <%= form.label :permission %>
      <%= form.select :permission, options_for_select([['Read Only', 'read-only'], ['Read Write', 'read-write']]), selected: @file_upload.permission %>
    </div>
    <div>
      <%= form.label :folder_id, "Select Folder" %>
      <%= form.collection_select :folder_id, current_user.folders, :id, :name, include_blank: true %>
  </div>
    <div>
      <%= form.submit "Upload File" %>
    </div>
  <% end %>
  

app/views/file_uploads/edit.html.erb
<%= form_with(model: @file_upload, local: true) do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.label :file %>
        <%= form.file_field :file %>
    </div>
    <div>
        <%= form.label :permission %>
        <%= form.select :permission, options_for_select([['Read Only', 'read-only'], ['Read Write', 'read-write']], selected: @file_upload.permission) %>
    </div>
    <div>
        <%= form.submit "Update File" %>
    </div>
<% end %>
  

app/views/file_uploads/index.html.erb
<h1>Your Files</h1>

<%= link_to "Upload File", new_folder_file_upload_path(@folder) %>

<ul>
    <% @file_uploads.each do |file_upload| %>
        <li>
            <%= link_to file_upload.name, folder_file_upload_path(file_upload.folder, file_upload) %>
            <%= link_to "Download", download_folder_file_upload_path(file_upload.folder, file_upload) %>
            <%= link_to "Share", new_folder_file_upload_file_share_path(file_upload.folder, file_upload) %>
        </li>
    <% end %>
</ul>

<%= link_to 'Back', root_path %>

app/views/file_uploads/new.html.erb
<h1>Upload File to <%= @folder.name %></h1>

<%= form_with model: [@folder, @file_upload], local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>
  <div>
    <%= form.label :permission %>
    <%= form.select :permission, options_for_select([['Read-Only', 'read-only'], ['Read-Write', 'read-write']]) %>
  </div>
  <div>
    <%= form.submit 'Upload' %>
  </div>
<% end %>

<%= link_to "Back", folder_path(@folder) %>

app/views/file_uploads/show.html.erb
<h1><%= @file_upload.name %></h1>

<p>
    <strong>File:</strong>
    <%= @file_upload.file.filename %>
</p>

<p>
    <strong>Current Permission:</strong>
    <%= @file_upload.permission %>
</p>

<%= form_with(model: @file_upload, url: folder_file_upload_path(@file_upload.folder, @file_upload), method: :patch) do |form| %>
    <div>
        <%= form.label :permission %>
        <%= form.select :permission, options_for_select(['read-only', 'read-write'], @file_upload.permission) %>
    </div>
    <div>
        <%= form.submit "Update Permission" %>
    </div>
<% end %>

<%= link_to 'Back', folder_file_uploads_path(@file_upload.folder) %>