config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  # root "posts#index"

  get 'users/index'
  get 'users/show'
  get 'home/index'
  devise_for :users
  root "home#index"

  resources :folders do
    resources :file_uploads, only: [:create, :index, :destroy, :new, :show, :update] do
      member do
        get 'download'
      end

      resources :file_shares, only: [:new, :create], controller: 'file_shares'
    end
  end

  resources :file_shares, only: [] do
    member do
      get 'download'
    end
  end

  resources :users, only: [:index, :show] do
    resources :folders, only: [:index] do
      resources :file_uploads, only: [:index]
    end

    member do
      patch :update_role
    end
  end

  resources :audit_logs, only: [:index]

  resources :notifications, only: [:index]
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  has_many :file_uploads, dependent: :destroy
  
  validates :name, presence: true
  validates :permission, inclusion: { in: %w[read-only read-write] }
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
    before_action :authenticate_user!

    def index
        @folders = current_user.folders
    end
  
    def new
        @folder = Folder.new
    end
  
    def create
        @folder = current_user.folders.build(folder_params)

        if @folder.save
            log_audit_action('create', 'Folder', @folder.id)
            redirect_to folders_path, notice: "Folder created successfully."
        else
            render :new
        end
    end
  
    def show
        @folder = Folder.find(params[:id])
        @file_uploads = @folder.file_uploads
    end

    def update
        @folder = current_user.folders.find(params[:id])

        if @folder.update(folder_params)
            log_audit_action('permission update', 'Folder', @folder.id)

            redirect_to folder_path(@folder), notice: "Folder updated successfully."
        else
            render :edit
        end
    end
  
    private
  
    def folder_params
        params.require(:folder).permit(:name, :permission)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/index.html.erb
<h1>Your Folders</h1>

<%= link_to "New Folder", new_folder_path %>

<ul>
  <% @folders.each do |folder| %>
    <li>
      <%= link_to folder.name, folder_path(folder) %> 
    </li>
  <% end %>
</ul>

<%= link_to 'Back', root_path %>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= form_with model: @folder, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :permission %>
    <%= form.select :permission, options_for_select(['read-only', 'read-write'], @folder.permission) %>
  </div>
  <div>
    <%= form.submit "Create Folder" %>
  </div>
<% end %>

<%= link_to "Back", folders_path %>

app/views/folders/show.html.erb
<h1><%= @folder.name %></h1>
<h2>Permissions: <%= @folder.permission || "No specific permissions set" %></h2>

<% if current_user.user? %>
  <%= form_with(model: @folder, url: folder_path(@folder), method: :patch) do |form| %>
    <div>
      <%= form.label :permission %>
      <%= form.select :permission, options_for_select(['read-only', 'read-write'], @folder.permission) %>
    </div>
    <div>
      <%= form.submit "Update Permission" %>
    </div>
  <% end %>
<% end %>

<%= link_to "Upload File", new_folder_file_upload_path(@folder) %>

<ul>
  <% @file_uploads.each do |file_upload| %>
    <li>
      <%= link_to file_upload.name, folder_file_upload_path(file_upload.folder, file_upload) %>
      <%= link_to "Download", download_folder_file_upload_path(file_upload) %>
      <%= link_to "Share", new_folder_file_upload_file_share_path(file_upload.folder, file_upload) %>
    </li>
  <% end %>
</ul>

<%= link_to "Back", folders_path %>