config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  # root "posts#index"

  get 'users/index'
  get 'users/show'
  get 'home/index'
  devise_for :users
  root "home#index"

  resources :folders do
    resources :file_uploads, only: [:create, :index, :destroy, :new, :show, :update] do
      member do
        get 'download'
      end

      resources :file_shares, only: [:new, :create], controller: 'file_shares'
    end
  end

  resources :file_shares, only: [] do
    member do
      get 'download'
    end
  end

  resources :users, only: [:index, :show] do
    resources :folders, only: [:index] do
      resources :file_uploads, only: [:index]
    end

    member do
      patch :update_role
    end
  end

  resources :audit_logs, only: [:index]

  resources :notifications, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :file_uploads, dependent: :destroy
  has_many :folders, dependent: :destroy
  has_many :file_shares, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ROLES = %w[admin user guest]

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= 'user'
  end

  def admin?
    role == 'admin'
  end

  def user?
    role == 'user'
  end

  def guest?
    role == 'guest'
  end

  def increment_failed_login_attempts
    increment!(:failed_login_attempts)
  end

  def reset_failed_login_attempts
    update(failed_login_attempts: 0)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin!
  before_action :set_user, only: [:show, :update_role]

  def index
    @users = User.all
  end

  def show
    @folders = @user.folders.includes(:file_uploads)
  end

  def update_role
    if current_user.admin? && @user.update(user_params)
        log_audit_action('user permission update', 'User', @user.id)
        redirect_to user_path(@user), notice: 'User updated successfully.'
    else
      redirect_to user_path, alert: 'Failed to update the user role'
    end
  end

  private

  def authorize_admin!
    redirect_to root_path, alert: "Not authorized." unless current_user.admin?
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email, user_path(user) %>
    </li>
  <% end %>
</ul>

<%= link_to "Back", root_path %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<h2>Current Role: <%= @user.role%>
<%= form_with(model: @user, url: update_role_user_path(@user), method: :patch) do |form| %>
  <div>
    <%= form.label :role %>
    <%= form.select :role, options_for_select(['admin', 'user', 'guest'], @user.role) %>
  </div>
  <div>
    <%= form.submit 'Update Role' %>
  </div>
<% end %>

<h2>Folders</h2>
<% @folders.each do |folder| %>
  <h2><%= folder.name %></h2>
  <ul>
    <% folder.file_uploads.each do |file_upload| %>
      <li>
        <%= file_upload.name %>
        <%= link_to "Download", download_folder_file_upload_path(file_upload.folder, file_upload) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= link_to "Back to Users", users_path %>