config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  # root "posts#index"

  get 'users/index'
  get 'users/show'
  get 'home/index'
  devise_for :users
  root "home#index"

  resources :folders do
    resources :file_uploads, only: [:create, :index, :destroy, :new, :show, :update] do
      member do
        get 'download'
      end

      resources :file_shares, only: [:new, :create], controller: 'file_shares'
    end
  end

  resources :file_shares, only: [] do
    member do
      get 'download'
    end
  end

  resources :users, only: [:index, :show] do
    resources :folders, only: [:index] do
      resources :file_uploads, only: [:index]
    end

    member do
      patch :update_role
    end
  end

  resources :audit_logs, only: [:index]

  resources :notifications, only: [:index]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>CSP</h1>

<% if user_signed_in? %>
    <% if current_user.admin? %>
        <%= link_to 'View Users', users_path %>
        <%= link_to 'View Audit Logs', audit_logs_path %>
        <%= link_to 'View Notifications', notifications_path %>
    <% end %>

    <% if current_user.user? %>
        <h2>Folders</h2>
        <%= link_to 'View Folders', folders_path %>
    <% end %>

    <% if current_user.guest? || current_user.user? %>
        <h2>Shared Files</h2>
        <ul>
            <% current_user.file_shares.includes(:file_upload).each do |file_share| %>
            <li>
                <%= file_share.file_upload.name %>
                <%= link_to 'Download', download_file_share_path(file_share), method: :get %>
            </li>
            <% end %>
        </ul>
    <% end %>
<% end %>